quarkus.http.port=${PORT:8090}
quarkus.langchain4j.ai.gemini.api-key=${GEMINI_API_KEY:}
quarkus.langchain4j.ai.gemini.chat-model.model-id=${GEMINI_MODEL:gemini-2.5-flash}
quarkus.langchain4j.log-requests=true
quarkus.langchain4j.log-responses=true

%test.quarkus.http.test-port=0
%test.quarkus.http.port=0
