quarkus.http.port=8081

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${DB_USER:mcp_user}
quarkus.datasource.password=${DB_PASS:mcp_password}
quarkus.datasource.jdbc.url=${DB_URL:jdbc:postgresql://localhost:5432/mcp_db}
quarkus.flyway.migrate-at-start=true

app.master.key=${APP_MASTER_KEY:0123456789abcdef0123456789abcdef}

quarkus.hibernate-orm.sql-load-script=no-file

smallrye.jwt.new-token.lifespan=86400

quarkus.http.host=0.0.0.0
quarkus.http.cors.enabled=true



%test.quarkus.http.test-port=0
%test.quarkus.http.port=0
