# Puerto de MCP CLient
quarkus.http.port=8081

# Configuración del motor Gemini (Flash 1.5 por defecto)
# Configuracin del motor de IA (Gemini)
gemini.api.key=AIzaSyB1vpKOKh8ybP8hKNKvFLKXhgktLMlAnVA

