package org.acme.mcp.service;

import jakarta.enterprise.context.ApplicationScoped;
import jakarta.inject.Inject;
import org.acme.mcp.model.McpServerConfig;
import org.acme.mcp.model.User;
import org.acme.mcp.model.Workspace;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.UUID;

@ApplicationScoped
public class WorkspaceProvisionService {

    private static final Path GENERATED_DIR = Paths.get("generated", "workspaces");

    @Inject
    McpDeclarativeConfigService declarativeConfigService;

    @Inject
    WorkspaceService workspaceService;

    public Map<String, Object> preview(UUID userId) {
        Workspace workspace = workspaceService.getOrCreateDefault(userId);
        int port = workspace.runtimePort == null ? 8090 : workspace.runtimePort;
        List<McpServerConfig> servers = McpServerConfig.listByUserId(userId);
        String properties = toRuntimeProperties(port, servers);

        Map<String, Object> data = new LinkedHashMap<>(workspaceService.toMap(workspace));
        data.put("runtimePort", port);
        data.put("serverCount", servers.size());
        data.put("content", properties);
        data.put("nextStep", "Guarda y aplica esta configuracion, despues arranca workspace-runtime con el comando generado.");
        return data;
    }

    public Map<String, Object> apply(UUID userId) {
        User user = User.findById(userId);
        if (user == null) {
            throw new IllegalStateException("Usuario no encontrado.");
        }
        if (user.geminiKeyEnc == null || user.geminiKeyEnc.isBlank()) {
            throw new IllegalStateException("El usuario no tiene una API key de Gemini registrada.");
        }

        Workspace draftWorkspace = workspaceService.getOrCreateDefault(userId);
        int port = workspaceService.ensureRuntimePort(userId);
        List<McpServerConfig> servers = McpServerConfig.listByUserId(userId);
        String properties = toRuntimeProperties(port, servers);
        Path workspaceDir = GENERATED_DIR.resolve(draftWorkspace.id.toString());
        Path configPath = workspaceDir.resolve("workspace-runtime.properties");
        write(configPath, properties);

        String startupCommand = startupCommand(configPath, port);
        Workspace workspace = workspaceService.markProvisioned(userId, port, configPath.toAbsolutePath().toString(), startupCommand);

        Map<String, Object> data = new LinkedHashMap<>(workspaceService.toMap(workspace));
        data.put("serverCount", servers.size());
        data.put("content", properties);
        data.put("nextStep", "Arranca tu workspace-runtime y vuelve al chat. Ese runtime cargara quarkus-langchain4j-mcp de forma declarativa.");
        return data;
    }

    private String toRuntimeProperties(int port, List<McpServerConfig> servers) {
        StringBuilder builder = new StringBuilder();
        builder.append("# Workspace runtime generated by control-plane\n");
        builder.append("# Define tu propia API key antes de arrancar: $env:GEMINI_API_KEY=\"tu_clave\"\n\n");
        builder.append("quarkus.http.port=").append(port).append('\n');
        builder.append("quarkus.langchain4j.ai.gemini.api-key=${GEMINI_API_KEY:}\n");
        builder.append("quarkus.langchain4j.ai.gemini.chat-model.model-id=${GEMINI_MODEL:gemini-2.5-flash}\n");
        builder.append("quarkus.langchain4j.log-requests=true\n");
        builder.append("quarkus.langchain4j.log-responses=true\n\n");
        builder.append(declarativeConfigService.toProperties(servers));
        return builder.toString();
    }

    private String startupCommand(Path configPath, int port) {
        return "$env:GEMINI_API_KEY=\"<tu_clave>\"; .\\mvnw.cmd -pl workspace-runtime quarkus:dev -Dquarkus.http.port="
                + port
                + " -Dquarkus.config.locations=\""
                + configPath.toAbsolutePath().toUri()
                + "\"";
    }

    private void write(Path path, String content) {
        try {
            Files.createDirectories(path.getParent());
            Files.writeString(path, content, StandardCharsets.UTF_8);
        } catch (IOException e) {
            throw new IllegalStateException("No se pudo generar la configuracion del workspace runtime.", e);
        }
    }
}
